# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dae505c2871fbb8bdea1bc693f304525d6c8353b422dbeba3de1b52a7bc938f3ade65f7a9ce60bd53d88e93009bbf8138b4acb12d56edbd8ff3fde9b28641ae8

test:
  secret_key_base: cbeae17b5c1b5486e7eedcf8c611f447b4048e55258ddadafda982a2b3dd1088e343e31f17a6811fe4ee98972f333c44853c59c36b1d1d90762b061e324ba111

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
